league_oauth2_server:
    authorization_server:
        private_key: '%kernel.project_dir%/var/oauth/private.key'
        private_key_passphrase: '%env(string:OAUTH2_ENCRYPTION_KEY)%'
        encryption_key: '%env(string:OAUTH2_ENCRYPTION_KEY)%'
        access_token_ttl:     PT1H
        refresh_token_ttl:    P1M
        auth_code_ttl:        PT10M
        enable_client_credentials_grant: true
        enable_password_grant: true
        enable_refresh_token_grant: true
        enable_auth_code_grant: true
        require_code_challenge_for_public_clients: true
        enable_implicit_grant: true
    resource_server:
        public_key: '%kernel.project_dir%/var/oauth/public.key'
    scopes:
            available:
                - default
            default:
                - default
    persistence:
        doctrine: null
